app:
  resource: "@AppBundle/Controller/"
  type: annotation

categories:
  type: rest
  resource: AppBundle\Controller\CategoryController

warehouses:
  type: rest
  resource: AppBundle\Controller\WarehouseController

nelmio-api-doc:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /documentation